# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
#
# For optimal development experience, run Vite locally:
# 1. npm install
# 2. npm run dev
# This provides hot module replacement and faster rebuilds.

services:
  # Override Laravel Application for development
  app:
    build:
      context: .
      target: development
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - .:/var/www/html              # Mount entire project for development
      - /var/www/html/vendor         # Exclude vendor (use container's version)
      - /var/www/html/node_modules   # Exclude node_modules (use container's version)
      - /var/www/html/storage        # Exclude storage (use volume)
    
  # Add MailHog for email testing in development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: webhook_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP port for Laravel
      - "8025:8025"  # Web UI port for viewing emails
    networks:
      - webhook-network
